/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mariopoorty;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author fluff
 */
public class GatoUI extends javax.swing.JFrame {
    
    private boolean turnoX = true; // Indica si es turno de X; si es falso, es turno de O
    private JButton[][] botones = new JButton[3][3]; // Matriz para botones
    
    /**
     * Creates new form GatoUI
     */
    public GatoUI() {
        initComponents();
        inicializarTablero();
    }
    private void inicializarTablero() {
        botones[0][0] = btn00;
        botones[0][1] = btn01;
        botones[0][2] = btn02;
        botones[1][0] = btn10;
        botones[1][1] = btn11;
        botones[1][2] = btn12;
        botones[2][0] = btn20;
        botones[2][1] = btn21;
        botones[2][2] = btn22;

        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                botones[i][j].addActionListener(e -> botonPresionado((JButton) e.getSource()));
            }
        }
        turnoLabel.setText("Turno de: X"); // Indicar primer turno
    }
    
    private void botonPresionado(JButton boton) {
        if (!boton.getText().equals("")) {
            return; // Si el botón ya tiene X u O, no hacer nada
        }

        // Asignar X o O en el botón
        boton.setText(turnoX ? "X" : "O");

        // Revisar si alguien ganó
        if (verificarGanador()) {
            JOptionPane.showMessageDialog(this, "¡El jugador " + (turnoX ? "X" : "O") + " ha ganado!");
        } else if (esEmpate()) {
            JOptionPane.showMessageDialog(this, "¡Empate!");
        } else {
            turnoX = !turnoX; // Cambiar de turno
            turnoLabel.setText("Turno de: " + (turnoX ? "X" : "O")); // Actualizar etiqueta de turno
        }
    }
    
    private boolean verificarGanador() {
        // Revisar filas, columnas y diagonales
        for (int i = 0; i < 3; i++) {
            if (botones[i][0].getText().equals(botones[i][1].getText()) && botones[i][0].getText().equals(botones[i][2].getText()) && !botones[i][0].getText().equals("")) {
                return true;
            }
            if (botones[0][i].getText().equals(botones[1][i].getText()) && botones[0][i].getText().equals(botones[2][i].getText()) && !botones[0][i].getText().equals("")) {
                return true;
            }
        }
        if (botones[0][0].getText().equals(botones[1][1].getText()) && botones[0][0].getText().equals(botones[2][2].getText()) && !botones[0][0].getText().equals("")) {
            return true;
        }
        if (botones[0][2].getText().equals(botones[1][1].getText()) && botones[0][2].getText().equals(botones[2][0].getText()) && !botones[0][2].getText().equals("")) {
            return true;
        }
        return false;
    }
    
    private boolean esEmpate() {
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                if (botones[i][j].getText().equals("")) {
                    return false;
                }
            }
        }
        return true;
    }

     public static void runner() {
        java.awt.EventQueue.invokeLater(() -> new GatoUI().setVisible(true));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GridLayout = new javax.swing.JPanel();
        btn00 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        turnoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GridLayout.setLayout(new java.awt.GridLayout(3, 3));

        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });
        GridLayout.add(btn00);
        GridLayout.add(btn01);
        GridLayout.add(btn02);
        GridLayout.add(btn10);
        GridLayout.add(btn11);
        GridLayout.add(btn12);
        GridLayout.add(btn20);
        GridLayout.add(btn21);
        GridLayout.add(btn22);

        turnoLabel.setText("Turno:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(GridLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(turnoLabel)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(turnoLabel)
                .addGap(42, 42, 42)
                .addComponent(GridLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        GridLayout.getAccessibleContext().setAccessibleName("");
        GridLayout.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn00ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GatoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GatoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GatoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GatoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GatoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GridLayout;
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JLabel turnoLabel;
    // End of variables declaration//GEN-END:variables
}
