/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mariopoorty;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author fluff
 */
public class JuegoCartasUI extends javax.swing.JFrame {
    private final CardGame game;
    private final JLabel[] playerCards; // Labels para mostrar las cartas de cada jugador
    private final JButton[] drawButtons; // Botones para repartir carta
    private final JLabel winnerLabel; // Etiqueta para mostrar al ganador
    private int playerCount;

    public JuegoCartasUI(int playerCount) {
        this.playerCount = playerCount;
        this.game = new CardGame();
        this.playerCards = new JLabel[playerCount];
        this.drawButtons = new JButton[playerCount];
        this.winnerLabel = new JLabel("El ganador se mostrará aquí");

        setupUI();
    }

    private void setupUI() {
        setTitle("Minijuego de Cartas");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        // Panel central: Cartas y botones de acción
        JPanel centerPanel = new JPanel();
        centerPanel.setLayout(new GridLayout(playerCount, 2, 10, 10));

        for (int i = 0; i < playerCount; i++) {
            JLabel cardLabel = new JLabel();
            cardLabel.setHorizontalAlignment(SwingConstants.CENTER);
            cardLabel.setVerticalAlignment(SwingConstants.CENTER);
            cardLabel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            playerCards[i] = cardLabel;

            JButton drawButton = new JButton("Repartir Carta");
            int playerIndex = i + 1;
            drawButton.addActionListener(e -> drawCardForPlayer(playerIndex));
            drawButtons[i] = drawButton;

            centerPanel.add(cardLabel);
            centerPanel.add(drawButton);
        }

        add(centerPanel, BorderLayout.CENTER);

        // Panel inferior: Ganador
        JPanel bottomPanel = new JPanel();
        bottomPanel.setLayout(new FlowLayout());
        bottomPanel.add(winnerLabel);

        JButton revealWinnerButton = new JButton("Revelar Ganador");
        revealWinnerButton.addActionListener(e -> revealWinner());
        bottomPanel.add(revealWinnerButton);

        add(bottomPanel, BorderLayout.SOUTH);
    }

    private void drawCardForPlayer(int player) {
        String card = game.drawCard(player); // Obtiene la carta del jugador
        if (card != null) {
            try {
                String filePath = "E:/_repositorios/MarioPoorty/MarioPoorty/src/Data/" + card + ".png"; // Ruta correcta para el archivo
                ImageIcon cardImage = new ImageIcon(new ImageIcon(filePath).getImage().getScaledInstance(47, 69, Image.SCALE_SMOOTH));
                playerCards[player - 1].setIcon(cardImage);
                drawButtons[player - 1].setEnabled(false); // Desactiva el botón tras repartir
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cargar la imagen para la carta: " + card, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay más cartas en la baraja.");
        }
    }

    private void revealWinner() {
        int winner = game.determineWinner();
        if (winner != -1) {
            winnerLabel.setText("El ganador es el jugador " + winner + "!");
        } else {
            winnerLabel.setText("¡Empate!");
        }
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // Seleccionar cantidad de jugadores antes de abrir la UI
        Integer[] options = {2, 3, 4, 5, 6};
        Integer selectedPlayerCount = (Integer) JOptionPane.showInputDialog(
                null,
                "Seleccione la cantidad de jugadores:",
                "Configuración de jugadores",
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);

        if (selectedPlayerCount != null) {
            SwingUtilities.invokeLater(() -> {
                JuegoCartasUI ui = new JuegoCartasUI(selectedPlayerCount);
                ui.setVisible(true);
            });
        } else {
            System.exit(0); // Cierra si no se selecciona nada
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
